name: Atualizar site

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # Roda todo dia às 3h da manhã

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: pip install requests

    - name: Rodar script de geração
      run: python generate_index.py

    - name: Commitar mudanças
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Atualiza index automaticamente"
        git push
